name: Manual Build and Release

on:
  workflow_dispatch:   # 👈 enables the "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build installers
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
